name: Deploy to Hostinger

on:
  push:
    branches:
      - master  # o main según tu repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build project (opcional)
      run: |
        if [ -f package.json ]; then
          npm install
          npm run build
        fi

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USERNAME }}
        password: ${{ secrets.HOSTINGER_PASSWORD }}
        local-dir: ./build/  # Cambialo a ./ si es HTML/CSS puro
        server-dir: ${{ secrets.HOSTINGER_PATH }}
        protocol: ftp
